version: "3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: faceid

    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres-network

volumes:
  pgdata:

networks:
  postgres-network:
    driver: bridge
